namespace OpenTracker.Models.SequenceBreaks
{
    /// <summary>
    /// This enum type defines the sequence break type values.
    /// </summary>
    public enum SequenceBreakType
    {
        BlindPedestal,
        BonkOverLedge,
        BumperCaveHookshot,
        SpikeCave,
        TRLaserSkip,
        LanmolasBombs,
        HelmasaurKingBasic,
        ArrghusBasic,
        MothulaBasic,
        BlindBasic,
        KholdstareBasic,
        VitreousBasic,
        TrinexxBasic,
        BombDuplicationAncillaOverload,
        BombDuplicationMirror,
        BombJumpPoDHammerJump,
        BombJumpSWBigChest,
        BombJumpIPBJ,
        BombJumpIPHookshotGap,
        BombJumpIPFreezorRoomGap,
        DarkRoomDeathMountainEntry,
        DarkRoomDeathMountainExit,
        DarkRoomHC,
        DarkRoomAT,
        DarkRoomEPRight,
        DarkRoomEPBack,
        DarkRoomPoDDarkBasement,
        DarkRoomPoDDarkMaze,
        DarkRoomPoDBossArea,
        DarkRoomMM,
        DarkRoomTR,
        FakeFlippersFairyRevival,
        FakeFlippersQirnJump,
        FakeFlippersScreenTransition,
        FakeFlippersSplashDeletion,
        WaterWalk,
        WaterWalkFromWaterfallCave,
        SuperBunnyMirror,
        SuperBunnyFallInHole,
        CameraUnlock,
        DungeonRevive,
        FakePowder,
        Hover,
        MimicClip,
        ToHHerapot,
        SPSpeckyClip,
        IPIceBreaker
    }
}
