namespace OpenTracker.Models.Enums
{
    public enum RegionID
    {
        LightWorld,
        HyruleCastleSecondFloor,
        DarkWorldWest,
        DarkWorldSouth,
        DarkWorldEast,
        DarkWorldSouthEast,
        DarkWorldWitchArea,
        MireArea,
        DeathMountainWestBottom,
        DeathMountainWestTop,
        DeathMountainEastBottom,
        DeathMountainEastTop,
        DarkDeathMountainTop,
        DarkDeathMountainEastBottom,
        DarkDeathMountainWestBottom,
        TurtleRockTunnel,
        HyruleCastle,
        Agahnim,
        EasternPalace,
        DesertPalace,
        TowerOfHera,
        PalaceOfDarkness,
        SwampPalace,
        SkullWoods,
        ThievesTown,
        IcePalace,
        MiseryMire,
        TurtleRockFront,
        TurtleRockBack,
        GanonsTower
    }
}
